name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Install Android SDK
      run: |
        # Instala dependências do sistema
        sudo apt-get update
        sudo apt-get install -y wget unzip

        # Download do SDK Tools
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk.zip
        mkdir -p $HOME/android-sdk
        unzip android-sdk.zip -d $HOME/android-sdk
        rm android-sdk.zip
        
        # Configura as variáveis de ambiente
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=\$PATH:\$ANDROID_HOME/tools:\$ANDROID_HOME/platform-tools" >> $GITHUB_ENV

    - name: Accept SDK Licenses
      run: |
        yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
        yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;35.0.0" "platforms;android-31" "platform-tools"

    - name: Build APK
      run: |
        # Comando para compilar seu APK
        # Aqui, substitua por seu comando de compilação
        # Por exemplo, se você tiver um script ou comando específico
        ./gradlew assembleDebug # ou qualquer comando que você utilize para build

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk # ajuste para o caminho correto do seu APK