name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        sudo apt-get install -y build-essential zlib1g-dev python3-distutils
        pip install buildozer cython

    - name: Set up Apache Ant
      run: |
        mkdir -p $HOME/ant
        cp -r tools/apache-ant-1.10.12/* $HOME/ant/
        echo "export ANT_HOME=$HOME/ant" >> $HOME/.bashrc
        echo "export PATH=\$PATH:\$ANT_HOME/bin" >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Install Android SDK
      run: |
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip -O android-sdk.zip
        unzip android-sdk.zip -d $HOME/android-sdk
        echo "export ANDROID_HOME=$HOME/android-sdk" >> $HOME/.bashrc
        echo "export PATH=\$PATH:\$ANDROID_HOME/tools:\$ANDROID_HOME/tools/bin:\$ANDROID_HOME/platform-tools" >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Accept SDK Licenses
      run: |
        yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses
        yes | $HOME/android-sdk/tools/bin/sdkmanager "build-tools;35.0.0" "platforms;android-31" "platform-tools"

    - name: Build APK
      run: |
        buildozer init
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug.apk
        path: bin/*.apk